### ISSUE TITLE
ValueError: The following settings are not supported: {'username': 'neo4j'}

### ISSUE THREAD

**Issue by wenjiaXu** [kdy2021/SR-RSKG#2]
Hi,

Thanks for fabulours work!

When I run the python import_kg.py, an error occurs:

Traceback (most recent call last):
  File "import_kg.py", line 9, in <module>
    password="123456"
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/database.py", line 115, in __init__
    profile = ServiceProfile(profile, **settings)
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/__init__.py", line 475, in __init__
    super(ServiceProfile, self).__init__(profile, **settings)
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/__init__.py", line 190, in __init__
    self._apply_settings(**settings)
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/__init__.py", line 512, in _apply_settings
    auth, user, password, **other)
  File "/BS/CAI/nobackup/anaconda3/envs/py37/lib/python3.7/site-packages/py2neo/__init__.py", line 293, in _apply_settings
    raise ValueError("The following settings are not supported: %r" % other)
ValueError: The following settings are not supported: {'username': 'neo4j'}

Could you please help to solve the problem?

Thank!

**Comment by DsglSheng** [comment]
> 

您好，请问您这个问题解决了吗，我这个问题解决了，neo4j图谱已经建成了，但是后续知识图谱如何做表示并参与到零样本学习中，您有了解过吗，或者相关的工作或代码可以推荐一下嘛，非常感谢您

**Comment by rongtongxueya** [comment]
您好，我最近也在做这个研究，请问您这个知识图谱如何参与到后续的零样本学习中请问您有什么建议学习的资料吗
